name: Android CI & Release

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Android SDK
        uses: android-actions/setup-android@b90f77c2e6f34769c90231a2f5f0e97b0c8242f7

      - name: Decode keystore from secret
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          mkdir -p keystore
          echo "KEYSTORE_BASE64" | base64 -d > keystore/release-key.jks

      - name: Set gradle.properties
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8" >> gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties
          echo "kotlin.code.style=official" >> gradle.properties
          echo "android.nonTransitiveRClass=true" >> gradle.properties
          echo "KEYSTORE_FILE=../keystore/release-key.jks" >> gradle.properties
          echo "KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD" >> gradle.properties
          echo "KEY_ALIAS=$KEY_ALIAS" >> gradle.properties
          echo "KEY_PASSWORD=$KEY_PASSWORD" >> gradle.properties

      - name: Grant permission to Gradle
        run: chmod +x ./gradlew

      - name: Run static analysis and tests
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ./gradlew clean \
            ktlintCheck \
            detekt \
            jacocoTestReport \
            assembleDebug \
            sonarqube \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.host.url=$SONAR_HOST_URL \
            --no-daemon

      - name: Build release APK
        run: ./gradlew assembleRelease --no-daemon

      - name: Upload release APK
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            app/build/reports/ktlint
            app/build/reports/detekt
            app/build/reports/jacoco