name: Android CI & Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Decode keystore from secret
        run: |
          mkdir -p keystore
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore/release-key.jks

      - name: Set gradle.properties
        run: |
          echo "org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8" >> gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties
          echo "kotlin.code.style=official" >> gradle.properties
          echo "android.nonTransitiveRClass=true" >> gradle.properties
          echo "KEYSTORE_FILE=../keystore/release-key.jks" >> gradle.properties
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> gradle.properties
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> gradle.properties
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> gradle.properties

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Upload build artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk

#  release:
#    name: Create GitHub Release
#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#    needs: build
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Download build artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: release-apk
#          path: .
#
#      - name: Calculate SHA256
#        id: sha
#        run: |
#          sha256=$(sha256sum app-release.apk | awk '{print $1}')
#          echo "sha=$sha256" >> $GITHUB_OUTPUT
#
#      - name: Create GitHub Release
#        uses: softprops/action-gh-release@v2
#        with:
#          tag_name: v${{ github.run_number }}
#          name: Release v${{ github.run_number }}
#          files: app-release.apk
#          body: |
#            ✅ Автоматический релиз после слияния в `main`.
#
#            🔐 SHA256: `${{ steps.sha.outputs.sha }}`
#
#            Скачайте APK и убедитесь в целостности.
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
